#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Update the CSM Manifest with artifacts from a given release
name: "Update CSM Manifest"

env:
  CHART_NAME: cray-product-catalog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (tag) to update in CSM manifest, eg v1.2.3'
        required: true
        default: 'v'
      csm-branch:
        description: 'Branch in the Cray-HPE/csm repo to update'
        required: true
        default: 'main'
      create-pr-draft:
        type: boolean
        description: 'Make the pull request a draft PR'
        required: false
        default: true

jobs:

  update-csm-manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        continue-on-error: false
        with:
          ref: ${{ github.event.inputs.version }}

      - uses: cardinalby/git-get-release-action@1.2.2
        id: release-info
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.event.inputs.version }}

      - name: Get release artifacts.json file
        uses: robinraju/release-downloader@v1.3
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.inputs.version }}
          fileName: "artifacts.json"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read artifacts JSON in
        id: set-json-vars
        run: |
          JSON=$(cat ./artifacts.json)
          echo "::set-output name=artifacts::${JSON//'%'/'%25'}"
          echo $JSON

      - run: |
          echo "Chart version: ${{fromJson(steps.set-json-vars.outputs.artifacts).CHART_VERSION}}"

      - name: Get auth token for PR creation
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.CSM_MANIFEST_AUTOUPDATER_APP_KEY }}
          app-id: ${{ secrets.CSM_MANIFEST_AUTOUPDATER_APP_ID }}

      - name: Checkout CSM repo
        uses: actions/checkout@v2
        with:
          token: ${{ steps.get-token.outputs.token }}
          repository: Cray-HPE/csm
          path: './csm'
          ref: ${{ github.event.inputs.csm-branch }}

      - name: Update manifest helm chart version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval --inplace 'with(.spec.charts[] | select(.name == strenv(CHART)) ; .version = strenv(VERSION))' ./csm/manifests/sysmgmt.yaml
        env:
          VERSION: "${{fromJson(steps.set-json-vars.outputs.artifacts).CHART_VERSION}}"
          CHART: ${{ env.CHART_NAME }}

      - name: Print Manifest File
        run: |
          cat ./csm/manifests/sysmgmt.yaml

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4.0.1
        with:
          token: ${{ steps.get-token.outputs.token }}
          path: ./csm
          branch: ${{ env.CHART_NAME }}/release-${{ github.event.inputs.version }}
          base: ${{ github.event.inputs.csm-branch }}
          delete-branch: true
          draft: ${{ github.event.inputs.create-pr-draft }}
          title: "[chore] Update manifest for ${{ env.CHART_NAME }} version: ${{ github.event.inputs.version }}"
          signoff: true
          assignees: ${{ github.actor }}
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          labels: |
            auto-generated
          commit-message: >
            This commit was autogenerated by the Update CSM Manifest workflow in the ${{ github.repository }} repository.
  
            See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.

            @${{ github.actor }} initiated the manifest update.
          body: >
            Autogenerated CSM Manifest update for ${{ env.CHART_NAME }}:

            * Release: [${{ env.CHART_NAME}} ${{ steps.release-info.outputs.name }}](${{ steps.release-info.outputs.html_url }}) (see release info below)

            * Repository: [${{ github.repository }}](https://github.com/${{ github.repository }})

            * Requested-by: @${{ github.actor }}

            * Autogenerated-by: [Update CSM Manifest workflow #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})


            # Release Info (${{ steps.release-info.outputs.name }})

            ${{ steps.release-info.outputs.body }}
          reviewers: |
            Cray-HPE/csm-release-managers

      - name: Generated Pull Request Info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
